import subprocess, sys

files_to_remove = [
    "test_body_content.py","test_cc_proxy.py","test_channel.py","test_com.py","test_com3.py",
    "test_com_quick.py","test_com_save_only.py","test_com_v2.py","test_direct.py",
    "test_hwp_save.py","test_models.py","test_multi_channel.py","test_new_key.py",
    "test_new_key2.py","test_open.py","test_open2.py","test_open3.py","test_py32.py",
    "check_156kb.py","check_J_patterns.py","check_all_rules.py","check_all_urls.py",
    "check_backup.py","check_binary_extract.py","check_cc_config.py","check_cc_db.py",
    "check_ccswitch.py","check_ccswitch2.py","check_ccswitch_detail.py","check_china_korean.py",
    "check_china_v2.py","check_china_v3.py","check_chinese_precise.py","check_claude_json.py",
    "check_claude_live.py","check_com.py","check_common_configs.py","check_current_text.py",
    "check_db_keys.py","check_file.py","check_ha.py","check_hwp_header.py","check_o_file.py",
    "check_original_binary.py","check_output_hwp.py","check_patterns.py","check_proofread_copy.py",
    "check_providers.py","check_quotes.py","check_remaining.py","check_rules.py",
    "check_spacing_both.py","check_text.py","check_with_script.py","check_xml_structure.py",
    "debug_geot.py","debug_goidda.py","diag_com_find.py","diag_deep.py","diag_dir.py",
    "diag_full.py","diag_ole.py",
    "fix_all_providers.py","fix_auth_conflict.py","fix_backup_keys.py","fix_cc_provider.py",
    "fix_claude_json.py","fix_claude_key.py","fix_claude_model.py","fix_current_provider.py",
    "fix_endpoints.py","fix_gemini_config.py","fix_iflytek_fields.py","fix_indent.py",
    "fix_json_final.py","fix_json_final_v2.py","fix_json_v2.py","fix_json_v3.py",
    "fix_json_v4.py","fix_json_v5.py","fix_locked_files.py","fix_missing_J.py",
    "fix_settings_json.py","fix_universal_providers.py","fix_url.py",
    "replace_all_keys.py","replace_keys_final.py","restore_o.py",
    "scan_old_key.py","search_o_everywhere.py",
    "setup_both_keys.py","setup_ccswitch_iflytek.py","setup_ccswitch_v2.py","setup_ribbon.py",
    "step_save_test.py","summarize_chinese.py",
    "sync_all_configs.py","sync_all_keys.py","sync_hwp.py","sync_hwp_files.py",
    "update_api_key.py","update_claude_key.py","utf16_search.py",
    "verify_J_detailed.py","verify_J_full.py","verify_K1694.py","verify_auth_fix.py",
    "verify_both.py","verify_both_final.py","verify_correction.py","verify_geot.py",
    "verify_inplace.py","verify_output.py","verify_spacing_both.py",
    "add_word_log.py","copy_o_for_proofread.py","copy_original_o.py","copy_rules.py","copy_rules2.py",
    "analyze_chinese_chars.py","analyze_compression.py","analyze_context_both.py","analyze_geot.py",
    "analyze_hwp_header.py","analyze_hwp_records.py","analyze_hwp_structure.py",
    "analyze_jl_deletions.py","analyze_missing_chinese.py","analyze_original.py",
    "analyze_precise_both.py","analyze_remaining.py","analyze_remaining_v2.py",
    "apply_quotes.py","apply_quotes_v2.py",
    "binary_diff.py","binary_quote_fix.py","binary_quote_fix_v2.py","binary_quote_fix_v3.py","binary_quote_fix_v4.py",
    "com_check_china.py","com_diagnose.py","com_export_hml.py","com_export_text.py",
    "com_find_backup.py","com_find_compare.py","com_find_dynamic.py","com_find_fresh.py",
    "com_find_original.py","com_initscan_v2.py","com_initscan_verify.py",
    "com_proofread.py","com_quote_methods.py","com_verify_find.py",
    "compare_JLK_full.py","compare_all_versions.py","compare_body.py","compare_chinese.py",
    "compare_chinese_both.py","compare_chinese_detail.py","compare_chinese_full.py",
    "compare_geot.py","compare_geot2.py","compare_hwp_files.py","compare_hwp_text.py",
    "compare_jl_files.py","compare_o_files.py","compare_streams.py",
    "deep_check_hwp.py","deep_compare.py","deep_search.py",
    "detailed_comparison_log.py",
    "extract_and_compare.py","extract_first_chinese.py","extract_ha.py","extract_hwp_text.py",
    "final_compare.py","final_comprehensive_verify.py","final_integrity_check.py","final_verify.py",
    "find_old_key.py","find_remaining.py","find_v2.py",
    "full_check.py","full_reapply.py","full_reapply_v2.py",
    "generate_final_log.py","generate_full_log.py",
    "hanja_full_compare.py",
    "hwp_allreplace.py","hwp_com_final.py","hwp_com_proofread.py","hwp_com_v2.py",
    "hwp_com_v3.py","hwp_com_v4.py","hwp_correction_system.py","hwp_findreplace.py",
    "hwp_macro_gen.py","hwp_ollama_proofread_detailed.py","hwp_ollama_proofread_v17_1.py",
    "hwp_proofread_fast.py","hwp_rule_only.py",
    "jkl_detailed_comparison.py","list_o_hwp_sizes.py","list_sajin.py",
    "olefile_check.py","raw_hex_compare.py",
    "reapply_china_fix.py","recheck_chinese_deletions.py",
    "run_K1694_full.py","run_both_v17_2.py","run_proofread.py","run_proofread_v17_1.py",
    "run_sadan_proofread.py","segment_detail_analysis.py",
    "CLAUDE.json","cache.json","cc-switch_settings_new.json",
    "added_items.txt","deleted_items.txt","deletion_analysis.txt",
    "compare_full.txt","compare_result.txt","com_proofread_log.txt",
    "hwp_ollama_proofread_log.txt","hwp_exported_text.txt",
    "cleanup_hwp_files.bat","force_cleanup_hwp.bat",
    "install_hwp2024_final.bat","install_hwp_compat.bat","install_hwp_ollama.bat",
    "manual_install_hwp.bat","run_hwp_proofread_sadan.bat",
    "fix_hwp2024_1603.bat",
]

removed = 0
for f in files_to_remove:
    result = subprocess.run(
        ["git", "rm", "--cached", "-q", f],
        capture_output=True, text=True, cwd=r"c:\Users\doris\.agent-skills"
    )
    if result.returncode == 0:
        removed += 1
        print(f"  removed: {f}")

print(f"\nTotal removed from tracking: {removed}")
